### PR TITLE
Spanish translation for Crow website

### PR DESCRIPTION
**Pull request by victorhck**
I have checked but you know, bugs sometimes happens!
Check if I didn't broke anything

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you a lot for your contribution. I tested it locally and it works as expected.
But all words in top menu in sum have a large length and because of this it looks differently than in other languages:
изображение
Is it possible to reduce number of characters a bit? It will be enough to reduce by at least 5 characters in any of the titles.

**Comment by victorhck** [comment]
well I have thinking on it, and it's a bit hard...

For Screenshots I can change from "Capturas de pantalla" (the right meaning) to Pantallazos (I don't like so much)

For ChangeLog from "Registro de cambios" to Novedades (it means like news or something like that) or even left the word in English (for geeks is a well known term)

Should be enough?

**Comment by Shatur** [comment]
It looks okay with `Novedades` and `Changelog`. Which change will be better?

**Comment by victorhck** [comment]
> It looks okay with `Novedades` and `Changelog`. Which change will be better?

Maybe Novedades, in that way all the text is translated and there's no a foreign word in the middle (IMHO)

**Comment by Shatur** [comment]
Thank you a lot for your contribution.

**Comment by victorhck** [comment]
Hey! The translation it's online!! Checking any "bug"

> Thank you a lot for your contribution.

A pleasure! Your app it's a great tool.  :+1: 
(I'm thinking that maybe should be part of KDE software! :wink:  )

**Comment by Shatur** [comment]
@victorhck, I made some changes in the installation section. Please, check if the [Spanish version](https://crow-translate.github.io/es/#installation) looks okay.

**Comment by victorhck** [comment]
> @victorhck, I made some changes in the installation section. Please, check if the [Spanish version](https://crow-translate.github.io/es/#installation) looks okay.

Check #2 if it's ok

**Comment by victorhck** [comment]
> @victorhck, I made some changes in the installation section. Please, check if the [Spanish version](https://crow-translate.github.io/es/#installation) looks okay.

Check #1 if it's ok

**Comment by victorhck** [comment]
> @victorhck, I made some changes in the installation section. Please, check if the [Spanish version](https://crow-translate.github.io/es/#installation) looks okay.

Check #2 if it's ok

**Pull request merged**
